version: '3'
services:
    auth:
        image: lthummus/auththingie
        volumes:
            - ./auththingie_config.conf:/auththingie_config.conf
        environment:
            - AUTHTHINGIE_CONFIG_FILE_PATH=/auththingie_config.conf
        labels:
            traefik.enable: true
            traefik.frontend.rule: "Host: auth.example.com"
            traefik.port: 9000

    traefik:
        image: traefik
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik.toml:/etc/traefik/traefik.toml
        ports:
            - 80:80
            - 443:443
            - 8080:8080

    sample:
        image: lthummus/samplesite
        labels:
            traefik.enable: true
            traefik.frontend.rule: "Host: test.example.com"
            traefik.frontend.auth.forward.address: "http://auth:9000/auth"
            traefik.port: 8000
