version: '3'
services:
    auth:
        build: .
        ports: 
            - 9000:9000
            - 9443:9443
        volumes:
            - ./traefikcop_config.conf:/traefikcop_config.conf
        environment:
            - CONFIG_FILE_PATH=/traefikcop_config.conf
        labels:
            traefik.enable: true
            traefik.frontend.rule: "Host: auth.example.com"
            traefik.port: 9000

    traefik:
        image: traefik
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik.toml:/etc/traefik/traefik.toml
        ports:
            - 80:80
            - 443:443
            - 8080:8080

    simple:
        image: python:2.7
        command:
            - "python"
            - "-m"
            - "SimpleHTTPServer"
        ports:
            - 8000:8000 
        labels:
            traefik.enable: true
            traefik.frontend.rule: "Host: test.example.com"
            traefik.frontend.auth.forward.address: "http://auth:9000/auth"
            traefik.port: 8000
